import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      nome: 'admin',
      email: 'admin@example.com',
      senha: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      nome: 'John',
      email: 'user@example.com',
      senha: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  products: [
    {
      // _id: '1',
      name: 'Apoio de Pulso',
      slug: 'apoio-de-pulso',
      image: '/images/Apoio_de_Pulso.png',
      brand: 'comfort tech',
      category: 'acessórios',
      description:
        'Apoio de pulso ergonômico para conforto durante o uso do teclado.',
      price: 24.99,
      countInStock: 0,
      rating: 4.0,
      numReviews: 5,
    },
    {
      // _id: '2',
      name: 'Porta-copos (descanso de copos)',
      slug: 'porta-copos',
      image: '/public/Images/Porta_Copos.png',
      brand: 'home decor',
      category: 'acessórios',
      description: 'Conjunto de porta-copos elegantes para sua mesa.',
      price: 14.99,
      countInStock: 30,
      rating: 4.5,
      numReviews: 10,
    },
    {
      //  _id: '3',
      name: 'HighBeam Pro - Iluminação Premium para Videoconferência',
      slug: 'highbeam-pro-iluminacao-premium',
      image: '/images/HighBeam_Pro_Iluminacao_Premium.png',
      brand: 'tech light',
      category: 'acessórios',
      description: 'Iluminação profissional para videoconferências.',
      price: 129.99,
      countInStock: 25,
      rating: 5.0,
      numReviews: 0,
    },
    {
      //  _id: '4',
      name: 'Prateleira de Mesa',
      slug: 'prateleira-mesa',
      image: '../',
      brand: 'design home',
      category: 'acessórios',
      description: 'Prateleira versátil para otimizar seu espaço de trabalho.',
      price: 59.99,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
    },
    {
      //  _id: '5',
      name: 'Prateleira de Mesa em Nogueira Preta',
      slug: 'prateleira-mesa-nogueira-preta',
      image: '/public/Images/Prateleira_Mesa_Nogueira_Preta.png',
      brand: 'design home',
      category: 'acessórios',
      description: 'Elegante prateleira de mesa em nogueira preta.',
      price: 79.99,
      countInStock: 15,
      rating: 4.0,
      numReviews: 10,
    },
    {
      //  _id: '6',
      name: 'Caderno Anotações',
      slug: 'caderno-anotacoes',
      image: '/images/c1.jpg', //c1 = caderno de anotaçao
      brand: 'caderno skill',
      category: 'acessórios',
      description: 'high quality product',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      //  _id: '7',
      name: 'Laptop Suporte',
      slug: 'laptop-suporte',
      image: '/images/Laptop_Suporte.jpg',
      brand: 'support tech',
      category: 'acessórios',
      description: 'ergonomic laptop support',
      price: 80,
      countInStock: 15,
      rating: 4.2,
      numReviews: 8,
    },
    {
      //  _id: '8',
      name: 'Luzes de Vídeo para Conferência',
      slug: 'luces-video-conferencia',
      image: 'images/Luzes_video_conferencia.jpg',
      brand: 'video lights co.',
      category: 'eletrônicos',
      description: 'high-quality video conference lights',
      price: 150,
      countInStock: 12,
      rating: 4.8,
      numReviews: 15,
    },
    {
      //  _id: '9',
      name: 'Mouse Pad Preto',
      slug: 'mouse-pad-preto',
      image: 'images/mouse_pad_preto.jpg',
      brand: 'black pad',
      category: 'acessórios',
      description: 'simple and elegant black mouse pad',
      price: 15,
      countInStock: 20,
      rating: 4.0,
      numReviews: 5,
    },
    {
      //  _id: '10',
      name: 'Suporte Headfone',
      slug: 'suporte-headfone',
      image: 'images/Suporte_headfone.jpg',
      brand: 'audio stand',
      category: 'acessórios',
      description: 'headphone stand with sleek design',
      price: 25,
      countInStock: 18,
      rating: 4.7,
      numReviews: 12,
    },
    {
      //  _id: '11',
      name: 'Planta de Mesa',
      slug: 'planta-mesa',
      image: 'images/Planta_mesa.png',
      brand: 'green decor',
      category: 'decoração',
      description: 'artificial desktop plant for decoration',
      price: 30,
      countInStock: 25,
      rating: 4.5,
      numReviews: 9,
    },
    {
      //  _id: '12',
      name: 'Suporte Vertical de Laptop',
      slug: 'suporte-vertical-laptop',
      image: 'images/Suporte_vertical_laptop.jpg',
      brand: 'vertical tech',
      category: 'acessórios',
      description: 'vertical laptop stand for space-saving',
      price: 45,
      countInStock: 14,
      rating: 4.3,
      numReviews: 11,
    },
    {
      //  _id: '13',
      name: 'Mesa Regulável',
      slug: 'mesa-regulavel',
      image: 'images/Mesa_regulavel.jpg',
      brand: 'adjustable desk co.',
      category: 'móveis',
      description: 'adjustable desk for ergonomic workspace',
      price: 200,
      countInStock: 8,
      rating: 4.9,
      numReviews: 20,
    },
  ],
};

export default data;
