import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  products: [
    {
      _id: '1',
      name: 'Apoio de Pulso',
      slug: 'apoio-de-pulso',
      image: '/images/Apoio_de_Pulso.png',
      brand: 'comfort tech',
      category: 'acessórios',
      description:
        'Apoio de pulso ergonômico para conforto durante o uso do teclado.',
      price: 24.99,
      countInStock: 0,
      rating: 4.0,
      numReviews: 5,
    },
    {
      _id: '2',
      name: 'Porta-copos (descanso de copos)',
      slug: 'porta-copos',
      image: '/public/Images/Porta_Copos.png',
      brand: 'home decor',
      category: 'acessórios',
      description: 'Conjunto de porta-copos elegantes para sua mesa.',
      price: 14.99,
      countInStock: 30,
      rating: 4.5,
      numReviews: 10,
    },
    // {
    //   // _id: '3',
    //   name: 'HighBeam Pro - Iluminação Premium para Videoconferência',
    //   slug: 'highbeam-pro-iluminacao-premium',
    //   category: 'acessórios',
    //   image: '/images/HighBeam_Pro_Iluminacao_Premium.png',
    //   price: 129.99,
    //   countInStock: 25,
    //   brand: 'tech light',
    //   rating: null,
    //   numReviews: null,
    //   description: 'Iluminação profissional para videoconferências.',
    // },
    // {
    //   // _id: '4',
    //   name: 'Prateleira de Mesa',
    //   slug: 'prateleira-mesa',
    //   category: 'acessórios',
    //   image: '../',
    //   price: 59.99,
    //   countInStock: 20,
    //   brand: 'design home',
    //   rating: null,
    //   numReviews: null,
    //   description: 'Prateleira versátil para otimizar seu espaço de trabalho.',
    // },
    // {
    //   // _id: '5',
    //   name: 'Prateleira de Mesa em Nogueira Preta',
    //   slug: 'prateleira-mesa-nogueira-preta',
    //   category: 'acessórios',
    //   image: '/public/Images/Prateleira_Mesa_Nogueira_Preta.png',
    //   price: 79.99,
    //   countInStock: 15,
    //   brand: 'design home',
    //   rating: null,
    //   numReviews: null,
    //   description: 'Elegante prateleira de mesa em nogueira preta.',
    // },
    // {
    //   // _id: '6',
    //   name: 'Caderno Anotações',
    //   slug: 'caderno-anotacoes',
    //   category: 'acessórios',
    //   image: '/images/c1.jpg', //c1 = caderno de anotaçao
    //   price: 120,
    //   countInStock: 10,
    //   brand: 'caderno skill',
    //   rating: 4.5,
    //   numReviews: 10,
    //   description: 'high quality product',
    // },
    // {
    //   // _id: '7',
    //   name: 'Laptop Suporte',
    //   slug: 'laptop-suporte',
    //   category: 'acessórios',
    //   image: '/images/Laptop_Suporte.jpg',
    //   price: 80,
    //   countInStock: 15,
    //   brand: 'support tech',
    //   rating: 4.2,
    //   numReviews: 8,
    //   description: 'ergonomic laptop support',
    // },
    // {
    //   // _id: '8',
    //   name: 'Luzes de Vídeo para Conferência',
    //   slug: 'luces-video-conferencia',
    //   category: 'eletrônicos',
    //   image: 'images/Luzes_video_conferencia.jpg',
    //   price: 150,
    //   countInStock: 12,
    //   brand: 'video lights co.',
    //   rating: 4.8,
    //   numReviews: 15,
    //   description: 'high-quality video conference lights',
    // },
    // {
    //   // _id: '9',
    //   name: 'Mouse Pad Preto',
    //   slug: 'mouse-pad-preto',
    //   category: 'acessórios',
    //   image: 'images/mouse_pad_preto.jpg',
    //   price: 15,
    //   countInStock: 20,
    //   brand: 'black pad',
    //   rating: 4.0,
    //   numReviews: 5,
    //   description: 'simple and elegant black mouse pad',
    // },
    // {
    //   // _id: '10',
    //   name: 'Suporte Headfone',
    //   slug: 'suporte-headfone',
    //   category: 'acessórios',
    //   image: 'images/Suporte_headfone.jpg',
    //   price: 25,
    //   countInStock: 18,
    //   brand: 'audio stand',
    //   rating: 4.7,
    //   numReviews: 12,
    //   description: 'headphone stand with sleek design',
    // },
    // {
    //   // _id: '11',
    //   name: 'Planta de Mesa',
    //   slug: 'planta-mesa',
    //   category: 'decoração',
    //   image: 'images/Planta_mesa.png',
    //   price: 30,
    //   countInStock: 25,
    //   brand: 'green decor',
    //   rating: 4.5,
    //   numReviews: 9,
    //   description: 'artificial desktop plant for decoration',
    // },
    // {
    //   // _id: '12',
    //   name: 'Suporte Vertical de Laptop',
    //   slug: 'suporte-vertical-laptop',
    //   category: 'acessórios',
    //   image: 'images/Suporte_vertical_laptop.jpg',
    //   price: 45,
    //   countInStock: 14,
    //   brand: 'vertical tech',
    //   rating: 4.3,
    //   numReviews: 11,
    //   description: 'vertical laptop stand for space-saving',
    // },
    // {
    //   // _id: '13',
    //   name: 'Mesa Regulável',
    //   slug: 'mesa-regulavel',
    //   category: 'móveis',
    //   image: 'images/Mesa_regulavel.jpg',
    //   price: 200,
    //   countInStock: 8,
    //   brand: 'adjustable desk co.',
    //   rating: 4.9,
    //   numReviews: 20,
    //   description: 'adjustable desk for ergonomic workspace',
    // },
  ],
};

export default data;
